### ISSUE TITLE
Trenches destroy Trucks

### ISSUE THREAD

**Issue by Salbei2500** [gruppe-adler/TvT_Template_linearSD_example.VR#2]
On Round start, the Trenches from the round before destroy the trucks from the attacking side.

**Comment by nomisum** [comment]
🤦 

maybe deleting all trenches would be a solution. issue belongs to tvt_template though.

**Comment by Salbei2500** [comment]
This was the only thing I found with LSD. 
Maybe we should splitt it.

**Comment by nomisum** [comment]
next: modularized tvt modes :laughing: 

i doubt mcd will go this far
